# 3. Testcases with coverage criteria

Input:
Weapon
Target
Rolls

1) 
In:
Sword, 
Dog, 
Fumble

Out:
Attacker stumble

2) 
In:
Martial Art Fist Punch, 
Dog, 
Fumble

Out:
Attacker stumble

3)
In:
Sword, 
Dog, 
2x Success

Out:
Dog revices wounds

4) 
In:
Sword of Dog Slaying, 
Dog, 
Critical

Out:
Dog revices wounds

5) 
In:
Sword of Dog Slaying, 
Fisch, 
Critical

Out:
Fisch revices wounds

7) 
In:
Sword of Horse Slaying, 
Horse, 
2x Critical

Out:
Horse revices wounds

6) 
In:
Sword of Wale Slaying, 
Wale, 
2x Critical

Out:
Wale revices wounds

7) 
In:
Holy Sword, 
Dog, 
Critical

Out:
Dog revices wounds

8) 
In:
Holy Sword, 
Minor Deamon, 
2x Critical

Out:
Minor Deamon revices wounds

9) 
In:
Holy Sword, 
Big Deamon, 
2x Critical

Out:
Big Deamon revices wounds

10)
In:
Holy Sword, 
Boss Deamon, 
2x Critical

Out:
Boss Deamon revices wounds
